org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.workers.max=4

kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2g

android.useAndroidX=true
android.nonTransitiveRClass=true

ksp.incremental=false
ksp.incremental.interprocessor=false
